# Generated by Django 3.0.5 on 2020-05-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photos',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
