# Generated by Django 3.0.5 on 2020-05-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photos',
        ),
    ]
