# Generated by Django 3.0.5 on 2020-05-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
