# Generated by Django 3.0.5 on 2020-05-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200504_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='ImageDetail',
        ),
    ]
