# Generated by Django 3.0.5 on 2020-05-05 00:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200505_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color_disponnible',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('O', 'ORANGE'), ('R', 'RED'), ('G', 'GREEN'), ('B', 'BLACK'), ('W', 'WHITE')], max_length=1),
        ),
    ]
