# Generated by Django 3.0.5 on 2020-05-05 00:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200505_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='color',
            field=models.CharField(default='WHITE', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='color_disponnible',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('O', 'ORANGE'), ('R', 'RED'), ('G', 'GREEN'), ('B', 'BLACK'), ('W', 'WHITE')], max_length=10),
        ),
    ]
