# Generated by Django 3.0.5 on 2020-05-05 01:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200505_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetail',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='size_disponnible',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'XLARGE')], default='S', max_length=10),
            preserve_default=False,
        ),
    ]
