# Generated by Django 3.0.5 on 2020-05-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200505_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='previousfield',
            new_name='previous_price',
        ),
    ]
