# Generated by Django 3.0.5 on 2020-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200505_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='color',
            field=models.CharField(choices=[('O', 'ORANGE'), ('R', 'RED'), ('G', 'GREEN'), ('B', 'BLACK'), ('W', 'WHITE')], default='W', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
