# Generated by Django 3.0.5 on 2020-05-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_imagedetail_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetail',
            name='color',
            field=models.CharField(choices=[('O', 'ORANGE'), ('R', 'RED'), ('G', 'GREEN'), ('B', 'BLACK'), ('W', 'WHITE')], max_length=6),
        ),
    ]
