# Generated by Django 3.0.5 on 2020-05-07 00:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200506_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetail',
            name='color',
            field=models.CharField(choices=[('#800080', 'PURPLE'), ('#ff0000', 'RED'), ('#008000', 'GREEN'), ('#000000', 'BLACK'), ('#f2f2f2', 'WHITE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_disponnible',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('#800080', 'PURPLE'), ('#ff0000', 'RED'), ('#008000', 'GREEN'), ('#000000', 'BLACK'), ('#f2f2f2', 'WHITE')], max_length=100),
        ),
    ]
