# Generated by Django 3.0.5 on 2020-05-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_orderitem_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_core',
            field=models.CharField(choices=[('#800080', 'PURPLE'), ('#ff0000', 'RED'), ('#008000', 'GREEN'), ('#000000', 'BLACK'), ('#f2f2f2', 'WHITE')], default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='size_core',
            field=models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'XLARGE')], default=False, max_length=100),
        ),
    ]
