# Generated by Django 3.0.5 on 2020-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200507_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedetail',
            old_name='color',
            new_name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color_core',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_core',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
