# Generated by Django 3.0.5 on 2020-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200508_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_core_default',
            field=models.CharField(choices=[('#800080', 'PURPLE'), ('#ff0000', 'RED'), ('#008000', 'GREEN'), ('#000000', 'BLACK'), ('#f2f2f2', 'WHITE')], default='BLACK', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size_core_default',
            field=models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'XLARGE')], default='M', max_length=100),
            preserve_default=False,
        ),
    ]
