# Generated by Django 3.0.5 on 2020-05-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200508_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_core_default',
            new_name='image_color_default',
        ),
    ]
