# Generated by Django 3.0.5 on 2020-05-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_date_ordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
