# Generated by Django 3.0.5 on 2020-05-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
