# Generated by Django 3.0.5 on 2020-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(to='core.Coupon'),
        ),
    ]
