# Generated by Django 3.0.5 on 2020-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiration',
            field=models.BooleanField(default=False),
        ),
    ]
