# Generated by Django 3.0.5 on 2020-05-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_coupon_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
