# Generated by Django 3.0.5 on 2020-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimal_amount_required',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
