# Generated by Django 3.0.5 on 2020-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200510_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_evaluation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_now',
            field=models.DateTimeField(),
        ),
    ]
