# Generated by Django 3.0.5 on 2020-05-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200510_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
