# Generated by Django 3.0.5 on 2020-05-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_billingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingadress',
            name='adress1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='billingadress',
            name='adress2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='billingadress',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='billingadress',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='billingadress',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='billingadress',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='billingadress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingadress',
            name='zip',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAdress'),
        ),
    ]
