# Generated by Django 3.0.5 on 2020-05-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200512_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='adress1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
