# Generated by Django 3.0.5 on 2020-05-12 18:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200512_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingadress',
            name='country',
            field=django_countries.fields.CountryField(default='ma', max_length=2),
            preserve_default=False,
        ),
    ]
